dataset:
  name: zavod70
  input_video: data/interim/zavod70.mp4
  smoke_video: data/interim/zavod70-smoke.mp4

pipeline:
  name: no_vda
  profile: low-vram
  init:
    instance: null
    async_prefetch: false
    prefetch_queue_size: 1
  slam:
    keyframe_depth: metric3d-small
  post:
    depth_align_model: null
  frame_start: 0
  frame_end: 1000
  frame_skip: 1
  save_artifacts: true
  save_slam_map: true
  save_viz: false

output:
  smoke: artifacts/vipe/smoke
  full: artifacts/vipe/full
