#!/usr/bin/env python3
"""Render an unchanged camera path generated by the Nerfstudio Viewer."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from nerfstudio.scripts.render import RenderCameraPath


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--load-config", type=Path, required=True)
    parser.add_argument("--camera-path", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    load_config = args.load_config.expanduser().resolve()
    camera_path = args.camera_path.expanduser().resolve()
    output = args.output.expanduser().resolve()
    for path in (load_config, camera_path):
        if not path.is_file():
            raise FileNotFoundError(path)

    payload = json.loads(camera_path.read_text(encoding="utf-8"))
    if not payload.get("camera_path"):
        raise ValueError(f"Camera path has no rendered frames; use Viewer Generate Command first: {camera_path}")
    output.parent.mkdir(parents=True, exist_ok=True)

    print(f"Viewer path: {camera_path}")
    print(f"Viewer crop: {json.dumps(payload.get('crop'), sort_keys=True)}")
    print(f"Output: {output}")
    RenderCameraPath(
        load_config=load_config,
        camera_path_filename=camera_path,
        output_path=output,
    ).main()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
